# -*- coding: utf-8 -*-
"""analizador-maquillaje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Db5zZVg1P_-jRa2TUFegpKqmiPK2Hhf0
"""

# app.py
import streamlit as st
import nltk
import re
import nltk

st.set_page_config(page_title="Analizador de Clientes", layout="centered")

st.title("🔍 Analizador de Mensajes de Clientas")
st.markdown("Pega aquí un mensaje de WhatsApp o redes sociales de una clienta y te diremos qué tipo de servicio busca y qué tan interesada parece estar.")

mensaje = st.text_area("📩 Mensaje de la clienta:", height=200)

# Diccionario de palabras clave
maquillaje_dict = {
    "boda": "Maquillaje nupcial",
    "novia": "Maquillaje nupcial",
    "evento": "Maquillaje social / de gala",
    "noche": "Maquillaje nocturno",
    "sesión": "Maquillaje para fotos",
    "natural": "Look natural",
    "contouring": "Maquillaje profesional con contorno",
}

# Función de análisis
def analizar_mensaje(texto):
    texto = texto.lower()
    estilo = "No detectado"
    interes = "Bajo"

    for palabra, tipo in maquillaje_dict.items():
        if palabra in texto:
            estilo = tipo
            break

    if re.search(r"(precio|valor|cuánto|agendar|disponible|reservar)", texto):
        interes = "Alto"
    elif re.search(r"(consultar|duda|info)", texto):
        interes = "Medio"

    return estilo, interes

# Procesamiento
if mensaje:
    estilo, interes = analizar_mensaje(mensaje)
    st.subheader("🔎 Resultado del análisis:")
    st.write(f"**Tipo de maquillaje sugerido:** {estilo}")
    st.write(f"**Nivel de interés de la clienta:** {interes}")

    if interes == "Alto":
        st.success("🎯 Alta probabilidad de conversión. ¡Responde rápido y ofrece disponibilidad!")
    elif interes == "Medio":
        st.info("📌 Cliente interesada, pero no decidida. Ofrece claridad y opciones.")
    else:
        st.warning("⚠️ No se detecta intención clara. Podría ser solo curiosidad.")
